### ISSUE TITLE
Add support for decimal and double numbers in parameter control

### ISSUE THREAD

**Issue by cezar06** [jsakamoto/BlazingStory#50]
Currently, the parameter control for numbers only supports integers.
#### Feature request: Modify/Add parameter control to support decimal and double values in addition to integers.

**Comment by jsakamoto** [comment]
### Todo list

- [ ] When users click the "Set number" button, it is always initialized by `default(int)` even though the parameter type is not `int`.
- [ ] When users type a number text into the number input box with decimal points, the input box shows a validation error. (The `step` attribute must be set appropriately.)
- [ ] When users switch to the `null` on the nullable number input box, and the input box is empty, the input box shows a validation error. (It must be removed the `require` attribute when the `null` radio button is selected.)

**Comment by jsakamoto** [comment]
Hi @cezar06,
Thank you for your feedback.
Actually, I knew the numeric input control's behavior was not smart, but I could not improve it at that time.

However, I finally improved it to be the same as the behavior you expected. Could you try the latest version of the "Blazing Story"?

- https://www.nuget.org/packages/BlazingStory/1.0.0-preview.41#releasenotes-body-tab
